### ISSUE TITLE
3.17 - Adapt LCP tests after refactor of beacon

### ISSUE THREAD

**Issue by Miraeld** [wp-media/wp-rocket-e2e#124]
# Description
After refactoring the beacon script within WP-Rocket (https://github.com/wp-media/wp-rocket/issues/6764) the test won't pass as some classes have changed. 

# Scope a solution
https://github.com/wp-media/wp-rocket-e2e/blob/182f32cd0a71504df2c62e6b7b5d9641bd53544d/src/support/steps/lcp-beacon-script.ts#L72 should be changed to 
``` typescript
                const beacon = document.querySelector('[data-name="wpr-wpr-beacon"]');
```

**Comment by Mai-Saad** [comment]
After CR if e2e tests pass then we can merge
