### ISSUE TITLE
Hanna - E2E

### ISSUE THREAD

**Issue by MathieuLamiot** [wp-media/wp-rocket-e2e#158]
See main issue

**Comment by hanna-meda** [comment]
- [x] Create your access to the remote desktop and access it with VNC: https://www.notion.so/wpmedia/Remote-desktop-on-OVH-0b03ec9321524c8facdbdb714443126e?pvs=4

- [x] Generate an SSH key for your remote desktop user and retrieve it locally: https://www.notion.so/wpmedia/Remote-desktop-on-OVH-0b03ec9321524c8facdbdb714443126e?pvs=4#126ed22a22f080689565ecfbff8fe30f

- [x] Add it to the E2E Wordpress server:
ssh ubuntu@51.91.147.85 (to connect to E2E server)
sudo nano .ssh/authorized_keys (to manage the list of authorized keys on this server).

- [x] Git clone Rocket-E2E repository on your remote desktop user in "Documents".
cd Documents
git clone https://github.com/wp-media/wp-rocket-e2e

- [x] Configure Rocket-E2E (config file + plugin zips). I recommend uploading your local conf and zips to the server via [FTP](https://www.notion.so/wpmedia/Remote-desktop-on-OVH-0b03ec9321524c8facdbdb714443126e?pvs=4#122ed22a22f080d9ad16e73dfdb03786) and then, with SSH or VNC, copy those files into your rocket-e2e install on the remote desktop.
You might need to change the wp.config.ts for the SSH key location.
You might need to change ownership of the files. It is described on Notion as well.

- [x] Set up the installation with npm install and npx playwright (as explained [here](https://www.notion.so/wpmedia/Rocket-E2E-Test-Automation-using-Cucumber-Playwright-aecad10ae0c14a11aa609881a9d1230b?pvs=4))

- [x] Connect to the remote desktop via VNC, open a terminal there and run npm run test:e2e (it takes ~1 hour)

 - [x] Compare your HTML report with the reference one provided [here](https://wp-media.slack.com/archives/C05NH7JU4S2/p1729547844058519?thread_ts=1729513024.781269&cid=C05NH7JU4S2). Once you are confident your E2E remote environment is set up properly; share the HTML report in the thread as well to allow the team to compare all of them later on and identify flaky tests.
