### ISSUE TITLE
Step to delete WPR failing in smoke test

### ISSUE THREAD

**Issue by jeawhanlee** [wp-media/wp-rocket-e2e#163]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version ✅
- Used the search feature to ensure that the bug hasn’t been reported before ✅

**Describe the bug**
On develop branch, when running smoke test,  the delete-plugin test, fails to delete WP Rocket and thus, the step fails.

**To Reproduce**
1. Switch to develop
2. Run smoke test
3. See the first test failing for delete-plugin

**Expected behavior**
The test should delete WP Rocket from the env without failing.

**Screenshots**
![Image](https://github.com/user-attachments/assets/b6d7c787-5945-40fb-953d-6a241e60468c)

**Additional context**

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by MathieuLamiot** [comment]
Grooming discussed here: https://wp-media.slack.com/archives/C05NH7JU4S2/p1729520523432109
