### ISSUE TITLE
"Should links be clickable While Delay JS is enabled" is always failing because of waiting for getByRole('link', { name: 'About Us' })

### ISSUE THREAD

**Issue by MathieuLamiot** [wp-media/wp-rocket-e2e#167]

**Comment by jeawhanlee** [comment]
@MathieuLamiot On this one, I'm not sure there's anything to be done here,  the reason this is failing is because the delayjs test requires specific scripts:
- test:delayjs:genesis
- test:delayjs:flatsome
- test:delayjs:divi
- test:delayjs:astra

I ran `npm run test:delayjs:flatsome` on the remote desktop and it passes.

**Comment by MathieuLamiot** [comment]
We need to do something to don't have a failed test:
- Ideally, can the correct behavior be set in the "all tests" command? I don't know what makes the commands you mention special. Can't we run them as part of the complete test plan?
- If this is not possible, then the test must be excluded of the complete test plan. This is not ideal of course.

In any case, something needs to be done.

**Comment by jeawhanlee** [comment]
We can encapsulate this kind of test to be run with a single command like we do for WP Rocket [here](https://github.com/wp-media/wp-rocket/blob/94b081e909520cdcb295a8d0ca94dc8d4ffd4038/composer.json#L181). That would be a straight forward solution.

**Comment by jeawhanlee** [comment]
### Scope a solution ✅
There are 2 ways I see to handle this

#### Method 1

Create a new script
- Create an array to hold all script command and loop through them.

In https://github.com/wp-media/wp-rocket-e2e/blob/221c9d21605df18c9a96cb65509f71480f01cefa/package.json
  - Update the value of this [script](https://github.com/wp-media/wp-rocket-e2e/blob/221c9d21605df18c9a96cb65509f71480f01cefa/package.json#L13) to hold the path to the new script just created 

#### Method 2
In https://github.com/wp-media/wp-rocket-e2e/blob/221c9d21605df18c9a96cb65509f71480f01cefa/package.json#L13
- Chain all the scripts in a single command using &&

Estimate the effort 
[XS]
