### ISSUE TITLE
Fix tests related to Feature:Beacon script captures the right images on remote server

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket-e2e#172]
Tests under Feature:Beacon script captures the right images are always failing on the remote server

=> cmd to run these tests is `npm run test:lcp`

=> for desktop:
- seems no image on this page now "/lcp_bg_relative_attribute_incss/" ==> rocket-test-data review is needed => the style file which shall have BG images is not on the repo anymore `/rocket-test-data/styles/lcp_styles.css"`
![Image](https://github.com/user-attachments/assets/1b5cc15e-ca95-42e6-bb1f-d6acd2e5d1f3)

**Comment by Mai-Saad** [comment]
For desktop: Adding the file lcp_styles to rocket-test-data and rerunning the test after pulling the latest test data update on the test environment and revisit json expectation if needed

**Comment by Mai-Saad** [comment]
lcp desktop is now fixed, we just need to update test sites with latest rocket-test-data
![Image](https://github.com/user-attachments/assets/6ad7e0b5-087c-4a71-ada9-edc3190937ef)

**Comment by Mai-Saad** [comment]
Remain handling the mobile failures
![Image](https://github.com/user-attachments/assets/53928a77-04c8-4370-8c8c-f7ccba4041c0)

**Comment by Khadreal** [comment]
Do we have the templates for those mobile in rocket-data updated ?

**Comment by Mai-Saad** [comment]
> Do we have the templates for those mobile in rocket-data updated ?

yes same pages are already passing for desktop

**Comment by Mai-Saad** [comment]
running only mobile lcp or both mobile &desktop is working fine on dev commit 2f39a0cb6132ed023d47909fedb2dc2baea1a6fb
![Image](https://github.com/user-attachments/assets/625fe38c-3757-4640-a5ae-c080e361f701)

![Image](https://github.com/user-attachments/assets/6b86a4eb-0698-4ba9-b848-e939269a7aa8)

**Comment by Mai-Saad** [comment]
Using commit 80bde4edadef9cc888af8c90e689bb8ca53283e5 working fine as well (remote dektop is minimized local)![Image](https://github.com/user-attachments/assets/d97936d2-24e3-474e-8605-32578cc7e58b)
