### ISSUE TITLE
Clean up shall consider using 2020 whenever we change the theme while testing

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket-e2e#173]
Some tests may change active theme like in delayjs tests. At the same time, our LCP results are based on 2020 as an active theme.

Thus As a QA engineer, I'd like to consider the test clean-up to reset the system to its original state like before the test to have consistent results.

**Comment by hanna-meda** [comment]
Note:
When completing this task, please also consider removing the following [line](https://github.com/wp-media/wp-rocket-e2e/blob/2f39a0cb6132ed023d47909fedb2dc2baea1a6fb/src/features/performance-hints.feature#L23C1-L24C1), as it will no longer be necessary there. Thank you.

**Comment by jeawhanlee** [comment]
### Scope a solution ✅
- In https://github.com/wp-media/wp-rocket-e2e/blob/80bde4edadef9cc888af8c90e689bb8ca53283e5/utils/page-utils.ts
  - Add a new process to switch theme [here](https://github.com/wp-media/wp-rocket-e2e/blob/80bde4edadef9cc888af8c90e689bb8ca53283e5/utils/page-utils.ts#L576) We already have one that does this via the UI, but it would be nice to have this done via WP CLI
  - And lastly just like @hanna-meda stated above, remove this [line](https://github.com/wp-media/wp-rocket-e2e/blob/2f39a0cb6132ed023d47909fedb2dc2baea1a6fb/src/features/performance-hints.feature#L23C1-L24C1) as we will now activate 2020 theme before each scenario.

Estimate the effort ✅
[S]

**Comment by Mai-Saad** [comment]
> And lastly just like @hanna-meda stated above, remove this [line](https://github.com/wp-media/wp-rocket-e2e/blob/2f39a0cb6132ed023d47909fedb2dc2baea1a6fb/src/features/performance-hints.feature#L23C1-L24C1) as we will now activate 2020 theme before each scenario.

@jeawhanlee @hanna-meda  which theme do we switch to here? is this step just validating that new theme is activated successfully after switching?

**Comment by hanna-meda** [comment]
> which theme do we switch to here? is this step just validating that new theme is activated successfully after switching?

@Mai-Saad Here, as last step of scenario, we switch back to the 2020 theme to ensure the environment is left with the default theme. However, since a clean-up process will now handle this, this step becomes obsolete.
