### ISSUE TITLE
Code documentation: File headers documentation

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket-e2e#20]
**Is your feature request related to a problem? Please describe.**
Some .ts files may not be clear what is used for or how to use it, will be great to add a file  header comment  at the beginning of each file or at least unclear ones ex: https://github.com/wp-media/wp-rocket-e2e/blob/trunk/src/common/custom-world.ts

**Describe the solution you'd like**
Having something like 
```
/**
 * Summary. 
 *
 * Description. 
 *
 * @file   This files defines the MyClass class.
 * @since  x.x.x
 */
```

**Describe alternatives you've considered**

**Additional context**
- We can do the same for function(s) whenever needed

**Comment by CrochetFeve0251** [comment]
@MathieuLamiot having documentation on the functions and classes would be better than commenting files themselves as it is easier to maintain if we move one or multiple classes to a file to another.
