### ISSUE TITLE
Refactor src/common to avoid duplication, generalize models and facilitate evolutions

### ISSUE THREAD

**Issue by MathieuLamiot** [wp-media/wp-rocket-e2e#3]
**Context**

The wp-rocket-e2e project has a great potential to speed up our development processes: as suggested by @CrochetFeve0251 in https://github.com/wp-media/wp-rocket-e2e/issues/1, every developer could leverage it to automate testing and validation of acceptance criteria. This means that many people will perform small updates regularly on this repository. However, it is currently not up to standards, making it difficult to maintain properly overtime.

Several steps must be taken to make this codebase "production ready".

**Issue**

The src/common folder contains methods that can then be used to facilitate test implementation. However, it is currently quite complex and hard to maintain. 

- [ ]  A refacto of this section is needed so that multiple users (developers, QA) can easily make it evolve as the product and testing needs evolve.
- [ ]  The linter from #2 must return no errors when linting src/common. This check must be added in the CI.

**Observations**

Here are some observations that must be investigated and potentially enhanced:
- In test (*.spec.ts), we instantiate new pageUtils(page) and also things like new fileOptimization( page ). But isn't the second one already instantiated in the first one? Could we avoid a duplication here?
- Unify calls to locators: we find this.page.locator(xxx) but also this.locators.xxx which is the same thing: it's hard to follow!
- All src/common/sections looks like it could be abstracted: define a class with a constructor that takes a JSON listing items (similar to how this.selectors is initiated currently). Abstract methods like visit(), toggle( option, checked),  toggleAll, areAllOptionsEnabled() could be defined, without having to re-write them everytime we add an option. Let's think about how the code will be used: someone will add (or remove) an option in the plugin, and do the same in the test software: it needs to be straightforward like adding a few line in a JSON. It seems there is a refinement for the toggle function, depending if there is an "activate" property defined? -> I suggest to write a quick documentation to explain what the structure should be so that we validate it before developing it.

**Comment by jeawhanlee** [comment]
### Scope a solution ✅
Moving forward, Just like @MathieuLamiot stated, We will need to dissolve all the classes in `src/common/sections` into a single common class called `Sections` which will have a constructor that accepts 2 dependencies, `Page` object and a `JSON` that holds a static state of all selectors and also create generic methods for this class that will adapt the functionality for each section without having to recall the same logic with a different method name like we do at the moment.

We will also create a setter method with respective property for setting the new section to interact with in tests.:

```
set = async ( section: String ) => {
this.section = section;

return this;
}
```
which we can then call like: `section.set('file_optimization').enable('minify_css')`.

The JSON structure could look like this for example:
```
{
 'file_optimization': {
   'selectors': {
     'minify_css': {
        'checkbox': '#minify_css',
        'enable': 'label[for=minify_css]',
        'activate': 'text=Activate minify CSS'
    },
    'combine_css': {
        'checkbox': '#minify_concatenate_css',
        'enable': 'label[for=minify_concatenate_css]',
        'activate': 'text=Activate combine CSS'
    },
  }
 }
}
```
N:B if an option selector does not have the '`activate`' key, we can simple bail out in the new generic method to handle this.

Then we will remove instances of previous sections classes and pass the `Section` class as a dependency here: https://github.com/wp-media/wp-rocket-e2e/blob/30e12fa54d31364d6ccaac0dea0d2d9411afb285/utils/page.utils.ts#L23 and also in every recurrence in the tests. 

For better handling of DI, I think we could use [TSyringe](https://www.npmjs.com/package/tsyringe)

Estimate the effort ✅
[M]
