### ISSUE TITLE
Update tests codebase

### ISSUE THREAD

**Issue by jeawhanlee** [wp-media/wp-rocket-e2e#35]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Some times tests fail randomly, updating some of these tests will help reduce these fails.

**Additional context**
These are related sub tasks:
https://github.com/wp-media/wp-rocket-e2e/issues/32
https://github.com/wp-media/wp-rocket-e2e/issues/31

**Comment by MathieuLamiot** [comment]
@jeawhanlee Is this still on-going or should it be Ready to Review? Thanks
