### ISSUE TITLE
Visual regression & error logs testing for 3.16 templates

### ISSUE THREAD

**Issue by MathieuLamiot** [wp-media/wp-rocket-e2e#53]
**Context**

Rocket-E2E has tests to cover visual regression and console errors, used for 3.15 for example. We don't have similar tests covering 3.16 and its dedicated templates.
Templates for 3.16 include requirements for page-builders, which is something Rocket-E2E does not support currently.

**What needs to be done**

- [ ] Gather from the QA team the templates to test 3.16 against, and which ones need which page builder.
- [ ] For template without page builder, create tests in Rocket-E2E covering visual non-reg (partly inspired by what we already have, no WP rocket vs. WP Rocket enabled) and console errors. Warning: To properly cover this, we need to make sure the 3.16 front-end modification is being applied, which has some pre-requisite in the DB: a page will be optimized only if the right data is in the DB related to 3.16, so some work is needed there.
- [ ] For template with page builder, build a mechanism that: enable the page builder, run the test, then disable the page builder.
- [ ] Run Rocket-E2E tests for 3.15 to ensure this is working properly and validate with the QA team.

**Additional information**
Please, consider teaming up with @hanna-meda to do this, to introduce her and guide her through Rocket-E2E.

**Comment by Khadreal** [comment]
Please can we have more information for this ?

**Comment by MathieuLamiot** [comment]
I just added more details, as we discussed it this morning with @jeawhanlee, @Miraeld & @wp-media/qa-team.
There are 2 complex things here:
- Non-reg on 3.16 feature means that, for the pages to test, we have the right data in the DB (LCP/ATF) so that the WP Rocket version of the page contains the right front-end optimization.
- Support for page-builder based templates.

**Comment by Mai-Saad** [comment]
**Basic Test scenarios that we need to cover here:**

Scenario1: Should preload lcp 'x' image type in public post
Given: critical images are cleared
And: Preload is disabled
When: visit the page 'x'
Then: the beacon script is added to page source
And: the URL added to ATF table 
When:clear cache
And: visit the page 'x'
Then: LCP image is preloaded
And no console error
And no error in debug.log
And no visual regression

Scenario2: Shouldn't LL LCP/ATF images
Given: critical images are cleared
And: Preload is disabled
And: Lazyload feature is enabled
When: visit the page 'x'
Then: clear the cache
And: visit the page 'x'
Then: LCP and ATF images aren't LL

Scenario3: Should apply lcp optimization with different page builders
Given: builder 'x' is enabled
And: builder 'x' template is cached
And: Lazyload is enabled
When: clear cache
And: visit the builder 'x' page
Then: LCP image is preloaded
And: LCP/ATF are excluded from LL
And: no console error
And: no error in debug.log
And: no VR

Scenario4: Should apply lcp optimization with different themes => same as builder but with theme

Scenario5: shouldn't cause console error nor VR  with WPML
Given: WPML is enabled
And: Page with LCP/ATF is cached in 2 languages
When: visit the page in main language
then: LCP/ATF optimization is applied
And: no console error nor debug error nor VR
When: switch to sublanguage
then: LCP/ATF optimization is applied
And: no console error nor debug error nor VR
when: clear critical images
then: visit the page in main language
then: LCP/ATF script is injected
And: no console error nor debug error nor VR
When: switch to sublanguage
then: LCP/ATF script is injected
And: no console error nor debug error nor VR

Scenario6: Should warmup 1st 10 URLs on the home page with a fresh install
Scenario 7: Should warmup 1st 10 URLs on the home page after the update
Scenario 8: Should warmup 1st 10 URLs on the home page after changing the permalinks

Note:
- Scenarios can be executed on desktop and mobile view (but we need to make sure that a separate mobile cache is enabled)
- we can add some scenarios to validate the messages
- For test templates, already some were added to e2e , starting with lcp_
- For WPML , check directory and qs setup
