### ISSUE TITLE
Smoke test is failing on e2e env (needs investigation)

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket-e2e#54]
- When running e2e automated smoke tests on https://e2e.rocketlabsqa.ovh/ , some tests are failing due to error in debug.log => the error is related to WPML
=> the same error occurred when using 3.15.10 or 3.15.9 as new_release.zip
- Manual install of 3.15.10 or 3.15.9 causing error in debug.log
- Manual install/activate/enable features on https://new.rocketlabsqa.ovh/ is fine
- enabled plugins
![Screenshot from 2024-03-19 13-20-00](https://github.com/wp-media/wp-rocket-e2e/assets/76941962/bb3627db-d9be-4da7-becb-59647d79fada)
![Screenshot from 2024-03-19 13-19-55](https://github.com/wp-media/wp-rocket-e2e/assets/76941962/c24ac963-1ae9-4a2a-8ab4-42b29e2fbad8)

- related discussion https://wp-media.slack.com/archives/CUT7FLHF1/p1710844261624729?thread_ts=1710840346.710509&cid=CUT7FLHF1
- WP 6.4.3 and PHP[ 8.3.3]

**Comment by Mai-Saad** [comment]
The error didn't happen after update WPML to 4.6.9

**Comment by MathieuLamiot** [comment]
@Mai-Saad Can we close it then, or do you need to run smoke tests with older versions of WPML?

**Comment by Mai-Saad** [comment]
Smoke test on the trunk of e2e (commit fbbc0d9c7b90878b005d579c9285dc37d5aa053b) with 3.16.2  of wpr failed due to an error in debug.log while WPML is deactivated (using mai.e2e env)
[debug-wp-rocket-is-installed-and-activated.log](https://github.com/user-attachments/files/16124824/debug-wp-rocket-is-installed-and-activated.log) 
[npm run test smoke.txt](https://github.com/user-attachments/files/16125135/npm.run.test.smoke.txt)

**Comment by Mai-Saad** [comment]
Tried to run on Hanna.e2e env , 5 scenarios failed and 3 passed. (using e2e trunk commit b6606a9bcaaa6f82f3f40a05bb7294919b04ab6a
)
[hanna smoke latest 3 16.txt](https://github.com/user-attachments/files/16578559/hanna.smoke.latest.3.16.txt)
[debug-data-exported-correctly-on-latest-version.log](https://github.com/user-attachments/files/16578583/debug-data-exported-correctly-on-latest-version.log)
[debug-data-exported-correctly-on-previous-version.log](https://github.com/user-attachments/files/16578584/debug-data-exported-correctly-on-previous-version.log)
[debug-enable-all-features.log](https://github.com/user-attachments/files/16578585/debug-enable-all-features.log)
[debug-roll-back-from-the-tools-tab.log](https://github.com/user-attachments/files/16578586/debug-roll-back-from-the-tools-tab.log)
[debug-visit-homepage-and-other-page.log](https://github.com/user-attachments/files/16578588/debug-visit-homepage-and-other-page.log)
[debug-wp-rocket-is-installed-and-activated.log](https://github.com/user-attachments/files/16578589/debug-wp-rocket-is-installed-and-activated.log)
[debug-wp-rocket-is-installed-but-not-activated.log](https://github.com/user-attachments/files/16578590/debug-wp-rocket-is-installed-but-not-activated.log)
Videos /screenshots https://drive.google.com/file/d/1sTBVHiT6jCSIrD1aSzApxQT2o7JMF8PL/view?usp=sharing
[new_release.zip](https://github.com/user-attachments/files/16578658/new_release.zip)
[previous_stable.zip](https://github.com/user-attachments/files/16578661/previous_stable.zip)

@jeawhanlee can you please have a look :pray:

**Comment by MathieuLamiot** [comment]
@Mai-Saad Can you confirm that:
- For @hanna-meda it is working on her env
- Share your config file
Thanks 🙏

**Comment by Mai-Saad** [comment]
@MathieuLamiot Here is the config file
[wp.config.zip](https://github.com/user-attachments/files/16578703/wp.config.zip)

**Comment by hanna-meda** [comment]
Using the same zip files shared by Mai above, on hanna.e2e trunk commit [b6606a9](https://github.com/wp-media/wp-rocket-e2e/commit/b6606a9bcaaa6f82f3f40a05bb7294919b04ab6a), I had 3 scenarios failed and 5 passed.
[hanna.e2e_smoke_results.txt](https://github.com/user-attachments/files/16580122/hanna.e2e_smoke_results.txt)
[debug-visit-homepage-and-other-page.log](https://github.com/user-attachments/files/16580148/debug-visit-homepage-and-other-page.log)
[debug-data-exported-correctly-on-previous-version.log](https://github.com/user-attachments/files/16580149/debug-data-exported-correctly-on-previous-version.log)
[debug-data-exported-correctly-on-latest-version.log](https://github.com/user-attachments/files/16580150/debug-data-exported-correctly-on-latest-version.log)
[debug-roll-back-from-the-tools-tab.log](https://github.com/user-attachments/files/16580151/debug-roll-back-from-the-tools-tab.log)
[debug-data-imported-correctly.log](https://github.com/user-attachments/files/16580152/debug-data-imported-correctly.log)
[debug-wp-rocket-is-installed-and-activated.log](https://github.com/user-attachments/files/16580153/debug-wp-rocket-is-installed-and-activated.log)
[debug-enable-all-features.log](https://github.com/user-attachments/files/16580154/debug-enable-all-features.log)
Videos / Screenshots: https://drive.google.com/drive/folders/1aujEGKPzwikQxRnlJTvfmqNFafRhxoFG?usp=drive_link
Config file: 
[wp.config_hanna.ts.zip](https://github.com/user-attachments/files/16580163/wp.config_hanna.ts.zip)

**Comment by MathieuLamiot** [comment]
Quick summary of the reports:
- Both had 2 failures related to #127 (missing minify banner)
- Both had failures related to error/warnings in log files (wpr_debug_log_notice) for:
    - Scenario: Enable all features -> Looking at the logs, those are "already existing table" and "invalid_schedule". Very likely to be timing issues with async tasks. We need to prevent this from failing the tests.
    - Scenario: Roll back from the tools -> Looking at the logs, those are "already existing table" and` PHP Warning:  include(/var/www/html/hanna.e2e.rocketlabsqa.ovh/wp-content/plugins/wp-rocket/vendor/composer/../../inc/Engine/Common/Utils.php): Failed to open stream: No such file or directory` -> I would assume this is also timing things when deleting/creating some files and data. To be confirmed, and in which case, this should not be failing the tests.
    - Scenario: Visit homepage and other page -> Same thing
    
- Only @Mai-Saad had a fail on `Scenario: Data imported correctly` and `Scenario: Data exported correctly on previous version` related to `page.waitForLoadState: Timeout 30000ms exceeded.` -> Need to check the video exactly for what happens. @Mai-Saad Can you give access to the google drive folder you shared? Thanks

-> Table already existing to tackle here: https://github.com/wp-media/wp-rocket-e2e/issues/132
For the other "timing" errors, we would have to investigate them to see if we can prevent them, or if this is just something to ignore by Rocket-E2E.

**Comment by MathieuLamiot** [comment]
About the 2 errors seen specifically by @Mai-Saad: they are both about the browser waiting for the load event which seems not to fire.
Based on the experience we have with RUCSS, waiting for load event is often too strict as it won't fire if one resource is not downloaded fully (which can be the case if a script is still loading, etc.). We usually don't need the full page to be completely loaded, with all scripts and images and so on. I would suggest the following approach:
- Review usage of waitForLoadState('load', throughout the tool. For each occurrence:
    - Consider using another waitFor function instead, for instance: waitForSelector. This allows to only wait for a specific element (for instance the Settings Saved banner after saving changes) which will be less flaky.
<img width="462" alt="image" src="https://github.com/user-attachments/assets/e9689b43-dd81-4367-a210-79295fa9e733">

    - If the load event is necessary, introduce a retry mechanism so that, if the timeout is reached, we retry the last action.

**Comment by MathieuLamiot** [comment]
Closing this investigation as it will be solved by the following issues:
- #133 
- #67 
- #127
