### ISSUE TITLE
Build a test that checks if content is Lazyloaded while scrolling the page

### ISSUE THREAD

**Issue by MathieuLamiot** [wp-media/wp-rocket-e2e#56]
**Context**

To test 3.15 feature (Lazyload background CSS images), many manual tests are to open the page, check that the images that should be lazyloaded are not downloaded through the dev tool console. Then, scroll and check that those images get loaded in the process.
Currently, Rocket-E2E only handled visual regression. But we have no guarantee images are being lazyloaded.

**What needs to be done**
- [ ] Investigate the possibility to get the list of documents being loaded when opening a page (similar to what we manually do in the dev tool -> Network panel of Chrome for instance).
- [ ] Implement an E2E test that:
    - Open a page
    - Check that the images that should be lazyloaded are not loaded yet.
    - Scroll down the page
    - Check that the images that should be lazyloaded have been loaded.
- [ ] Gather from the QA team a list of template to run this test against, and for each, the list of images to be lazyloaded.
- [ ] Run the test against the templates and validate that it works as expected with the QA team.

**Additional information**
Please, consider teaming up with @hanna-meda to do this, to introduce her and guide her through Rocket-E2E.

**Comment by Khadreal** [comment]
### Scope a solution ✅
We need to have a list of images that should be lazyloaded for each templates, then create a page and assign the template
Then get all the image request when page is active and scroll to the bottom, in the end we use assert to confirm if the image for the template list is the same as the request.
### Estimate the effort ✅
[S]


### Steps
Scenario: Check lazyload image for template A
- Given All WPR settings is enabled
- Go to page that has template A on the frontend
- When I scroll to the bottom
- Check that the images that are supposed to be lazyloaded are lazyload
Repeat for other template

**Comment by jeawhanlee** [comment]
In addition, we need to assert that there are no request to get images on page load until the scroll begins, Other than this, LGTM.

**Comment by Khadreal** [comment]
It depends on the template, some templates might need to load at least one image if the image is in view on load

**Comment by MathieuLamiot** [comment]
My 2 cents: if the test is about checking that some images are correctly lazyloaded, I would suggest that:
- The list of images we set as "expected result" only contains images to actually lazyload (ie., not loaded before scrolling).
- We check the loaded content before scrolling, and after scrolling. The "expected result" images should all be in the difference.

**Comment by hanna-meda** [comment]
@Khadreal, had a look over this and noticed a small thing, the `@llimages` tag is not there. 
Secondly, and our apologies for this, we updated the templates you used in tests to include also some lcp images. So there are a few more images that need to be added to the test, please.
