### ISSUE TITLE
Switch LCP tests from API to test file

### ISSUE THREAD

**Issue by Miraeld** [wp-media/wp-rocket-e2e#71]
## Is your feature request related to a problem? Please describe.
The PSI API we use in the LCP tests isn't something we should do. In fact an API doesn't guarantee to be available at any moment + it sometimes doesn't respond the same answer at each try. 

## Describe the solution you'd like
We could generate a file which will take for granted as expected output for LCP + ATF. It could be generated at first from the PSI API, and later on reviewed, updated by the product/QA/Dev team

## Additional context

We already expect some templates on Rocket-E2E for LCP/ATF to fail against the PSI API. They have been manually investigated in the Slack channel #wpr-316-template-investigations. So the manual modifications to apply to the file of expected results can be guided based on those observations for each failing template.
We already have a file of expected results for the ATF. So we could reuse the same mechanism.

**Comment by Miraeld** [comment]
## Scope a solution
To implement this feature, we must generate results files. I link two files which are respectively the expected results for `desktop` and `mobile`. 
⚠ ‼ ⚠ Files have been generated by using the PSI API for LCP results. And they haven't been corrected when these ones are wrong. Please make sure to updated the results according to what we are expecting per template @wp-media/productrocket @wp-media/qa-team 

[expectedResultsDesktop.json](https://github.com/wp-media/wp-rocket-e2e/files/15270462/expectedResultsDesktop.json)
[expectedResultsMobile.json](https://github.com/wp-media/wp-rocket-e2e/files/15270463/expectedResultsMobile.json)

We will have to load files path: 
``` typescript
const lcpResultsDesktop = './support/results/expectedResultsDesktop.json';
const lcpResultsMobile = './support/results/expectedResultsMobile.json';
```

and use them with (to be adapter in our case for both file):
``` typescript
    const data = await fs.readFile(lcpResultsDesktop, 'utf8');
    const jsonData = JSON.parse(data);
```

Finally, we will need to adapt this part
https://github.com/wp-media/wp-rocket-e2e/blob/64648aaf5ab8a599febff3792e849ab40983d51d/src/support/steps/lcp-beacon-script.ts#L87-L113

to use our file instead of the API. 

Also, something important, as our JSON files are containing the list of templates to test, we don't need to keep a datatable within the `I visit the following urls in {string}` step (https://github.com/wp-media/wp-rocket-e2e/blob/trunk/src/features/lcp-beacon-script.feature#L13-L39)


## Development steps:
- [x] Generates expected results files
- [ ] Correct expected results files
- [ ] Change the test to use these files

## Effort estimation: S/M
## Can be peer-coded:No
## Is a refactor needed in that part of the codebase?
No

**Comment by jeawhanlee** [comment]
I see we already have viewport expectations in the `JSON` file, we need to remove the step that adds them in the datatable
[here](https://github.com/wp-media/wp-rocket-e2e/blob/18e39e8a9ff4c8a52674a4c39d6a8a18a4a9fda5/src/features/lcp-beacon-script.feature#L11) and [here](https://github.com/wp-media/wp-rocket-e2e/blob/18e39e8a9ff4c8a52674a4c39d6a8a18a4a9fda5/src/features/lcp-beacon-script.feature#L25) and by this we will need to update the steps.

We don't need the `fs` module to use the `JSON` file, we already support JSON resolving [here](https://github.com/wp-media/wp-rocket-e2e/blob/18e39e8a9ff4c8a52674a4c39d6a8a18a4a9fda5/tsconfig.json#L7) or the path could just be directly called like we do [here](https://github.com/wp-media/wp-rocket-e2e/blob/18e39e8a9ff4c8a52674a4c39d6a8a18a4a9fda5/utils/helpers.ts#L23)

After updating the grooming, LGTM

**Comment by Miraeld** [comment]
@jeawhanlee , I'm not sure we should delete the viewport expectation from the steps. 
In a way, removing it means in the code we will have to process both Desktop & Mobile together, while keeping it allows you to start either one of them. Which could be handy in the future if we need to run only desktop for example, for whatever other test we have to do. 

Don't you think ?


Otherwise, I've updated the grooming according your feedback

**Comment by jeawhanlee** [comment]
Not to delete the step but since we have a JSON file now, we should port all the viewport expectations there and updated the step to receive no datatable argument.

**Comment by Miraeld** [comment]
I've edited the grooming to add a note about this.

**Comment by Miraeld** [comment]
@piotrbak or @Mai-Saad / @hanna-meda 
Could it be possible for you to have a look to the two JSON Files linked to the grooming and correct what's was badly detected by Google PSI API. While waiting for this, I put this issue as Blocked as we can't do anything without a corrected version. 
(I've corrected some, we just want a second look and confirmation this is ok or not).

**Comment by Mai-Saad** [comment]
@Miraeld Thanks for the ticket. Please find updated files.
Thanks @hanna-meda for updating the files
[expectedResultsMobile_revised_updated.json](https://github.com/wp-media/wp-rocket-e2e/files/15294120/expectedResultsMobile_revised_updated.json)
[expectedResultsDesktop_revised_updated.json](https://github.com/wp-media/wp-rocket-e2e/files/15294121/expectedResultsDesktop_revised_updated.json)

**Comment by Miraeld** [comment]
@Mai-Saad thanks for the revisited version, I'll be able to finish the PR :)
