### ISSUE TITLE
Command `I disable all settings` requires cache tab which is an error on WPR 3.16

### ISSUE THREAD

**Issue by Miraeld** [wp-media/wp-rocket-e2e#73]
## Before submitting an issue please check that you’ve completed the following steps:
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

## Describe the bug
While running tests that requires the step `I disabled all settings` on WP Rocket 3.16, we have an error as it tries to access the `cache` tab [here](https://github.com/wp-media/wp-rocket-e2e/blob/fe5e7d33b66c53d9a2495b82272e2a3a95c68ca0/utils/page-utils.ts#L314-L319) which has been deleted on this newest version. 

## To Reproduce
1. Use WP Rocket 3.16
2. Run smoke tests
3. See error

## Expected behavior
It shouldn't go on a tab that doesn't exists anymore.
And the test shouldn't fail because of it. 

**Screenshots**

**Additional context**

**Acceptance Criteria (for WP Media team use only)**

**Comment by jeawhanlee** [comment]
### Scope a solution ✅
For the sake of Backward compatibility, we should do conditional checks on the cache section before performing actions on it.
`utils/page-utils.ts`
- In `disableAllOptions` & `enableAllOptions`
  - Add a conditional check on all sections before visiting.

`src/common/selectors.ts`
- In `selectors` object literal
  - Add the `cacheLoggedUser` property in `cache` to `addons`

`src/support/steps/general.ts`
- In `I save settings` step definition
  - Add a conditional check
  - If the section is cache, check it exists, if it doesn't, check if the option is cacheLoggedUser so the action can be performed on the addon section.

Estimate the effort ✅
[S]

**Comment by Khadreal** [comment]
LGTM
