### ISSUE TITLE
LCP Test does not fail when no result in DB

### ISSUE THREAD

**Issue by jeawhanlee** [wp-media/wp-rocket-e2e#82]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When running lcp tests, if there are not results in DB after page visits, test will log output but will not fail.

**To Reproduce**
1. Set the viewport dimension in test to something unsupported, this will cause the beacon to bail.
2. See logs in CLI `(No result from database for url)`
3. Tests will pass in the end.

**Expected behavior**
Tests should fail when there is no result in DB.

**Screenshots**

**Additional context**

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by MathieuLamiot** [comment]
discussed [here](https://wp-media.slack.com/archives/CUKB44GNN/p1715871609951069?thread_ts=1715867749.944169&cid=CUKB44GNN) and blocking #71
