### ISSUE TITLE
LCP tests failing for Mobile scenario

### ISSUE THREAD

**Issue by jeawhanlee** [wp-media/wp-rocket-e2e#83]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When the mobile scenario runs, page visits do not store lcp results in the db causing a console log `(No result from database for url)`

**To Reproduce**
1. Run npm run test:lcp
2. Wait for the mobile scenario to run
3. See logs in the CLI `(No result from database for url lcp_bg_inline_template)`
4. Check the database and see that there are no entry for the templates.

**Expected behavior**
There should be entries in the DB for visited templates.

**Screenshots**

**Additional context**
We use a helper plugin to return true for `wp_is_mobile` but this is not being activated before templates are visited, fixing this should fix this issue.

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by MathieuLamiot** [comment]
Discussed [here](https://wp-media.slack.com/archives/CUKB44GNN/p1715871173299429?thread_ts=1715867749.944169&cid=CUKB44GNN) and blocking #71

**Comment by jeawhanlee** [comment]
I've spent some of my time on grooming but I'm free to come back to this at the moment.
