### ISSUE TITLE
Add lcp templates

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket-e2e#88]
We need to add the following templates to the json of lcp => min-width not  handled 100% yet
- https://e2e.rocketlabsqa.ovh/lcp_picture_template/
desktop:
lcp{"/wp-content/rocket-test-data/images/test3.gif", '/rocket-test-data/images/lcp/testjpg2.jpg', '/rocket-test-data/images/testjpg3.jpg'}
atf{"/rocket-test-data/images/lcp/testwebp.webp", '/rocket-test-data/images/lcp/testjpeg.jpeg', '/rocket-test-data/images/paper.jpeg', "/test.png", '/rocket-test-data/images/1_BDCYb3Yx8exGZVu5lLRPNw.png', '/rocket-test-data/images/lcp/testavif.avif'}
enabled:false

- https://e2e.rocketlabsqa.ovh/lcp_picture_template2/
desktop:
lcp{'/rocket-test-data/images/paper.jpeg', '/rocket-test-data/images/lcp/testjpeg.jpeg', '/rocket-test-data/images/lcp/testwebp.webp'}
atf: {'/rocket-test-data/images/test3.gif', '/rocket-test-data/images/testjpg3.jpg', '/rocket-test-data/images/lcp/testjpg2.jpg'}
enabled:false
Mobile:
lcp{'/rocket-test-data/images/test3.gif', '/rocket-test-data/images/testjpg3.jpg', '/rocket-test-data/images/lcp/testjpg2.jpg'}

- https://e2e.rocketlabsqa.ovh/lcp_bg_img_in_section/
desktop/mobile:
lcp{https://e2e.rocketlabsqa.ovh/wp-content/uploads/2024/03/should_be_lcp_atf_image.jpg}
ATF []

- https://e2e.rocketlabsqa.ovh/lcp_section_template_relative/ 
desktop or mobile {lcp: '/wp-content/rocket-test-data/image/test3.webp', '/wp-content/rocket-test-data/image/file_example_JPG_100kB.jpg'}
atf:/wp-content/rocket-test-data/images/lcp/testjpg.jpg}

- https://e2e.rocketlabsqa.ovh/lcp_section_template2/
desktop or mobile {lcp: https://images.pexels.com/photos/67636/rose-blue-flower-rose-blooms-67636.jpeg?auto=compress&cs=tinysrgb&h=350
atf: /wp-content/rocket-test-data/images/lcp/testjpg.jpg}

**Comment by Mai-Saad** [comment]
New templates (need to confirm LCP matching PSI and our rules of preload):
https://e2e.rocketlabsqa.ovh/lcp_picture_type/
https://e2e.rocketlabsqa.ovh/lcp_picture_responsive_type/
https://e2e.rocketlabsqa.ovh/lcp_picture_relative/
https://e2e.rocketlabsqa.ovh/lcp_picture_media_type_mixed/

**Comment by Mai-Saad** [comment]
todo: check templates related to lcp that aren't added to the json file yet other than the ones above and add it's data at the json + needed page at e2e if it isn't there

**Comment by Mai-Saad** [comment]
Note for review/update data: use e2e env as sometimes ATF image at new.rockertlabs can be different than e2e.rocketlabs (may be due to different plugins)

**Comment by Mai-Saad** [comment]
More templates:
https://e2e.rocketlabsqa.ovh/lcp_bg_relative_attribute_incss/
https://e2e.rocketlabsqa.ovh/lcp_6599_template2/
https://e2e.rocketlabsqa.ovh/lcp_specialchar2/
https://e2e.rocketlabsqa.ovh/lcp_bg_img_in_header_template/
https://e2e.rocketlabsqa.ovh/lcp_6647_svgbg_template/

**Comment by MathieuLamiot** [comment]
@wordpressfan Hello. I see this is in progress for almost a week. Are there any blockers or on-going discussions? thanks

**Comment by MathieuLamiot** [comment]
@Miraeld Looks like this branch is a start: https://github.com/wp-media/wp-rocket-e2e/tree/feature/88-add-more-lcp-templates
