### ISSUE TITLE
e2e tests not working on mai.e2e env

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/wp-rocket-e2e#96]
Running e2e on mai.e2e results in being stuck at the step to install WPR

![Screenshot from 2024-05-31 10-10-40](https://github.com/wp-media/wp-rocket-e2e/assets/76941962/753ab32b-2f6b-4eab-ba39-6d0c75fc7c2a)
[b472fc00b379c1411c9767e1e7607253.webm](https://github.com/wp-media/wp-rocket-e2e/assets/76941962/8c3de671-b134-4d3e-aff9-d21f64f17d55)

tested using 3.16 zip , trunk of e2e

**Comment by MathieuLamiot** [comment]
So first of all, this is not linked to mai.e2e: I have been able to make it work on mai.e2e with this config file:

```
const WP_ADMIN_USER = {
    username: 'Piotr',
    password: '5KwKO()Vmih67Ob8Zccw!Lj5',
    localUsername: 'admin',
    localPassword: 'password',
    local: 'http://localhost:10013',
    live: 'http://mai.e2e.rocketlabsqa.ovh'
    // live: 'http://e2e.rocketlabsqa.ovh'
    // 
} as const;

const {
    WP_USERNAME = process.env.npm_config_env !== undefined ? WP_ADMIN_USER.localUsername : WP_ADMIN_USER.username,
    WP_PASSWORD = process.env.npm_config_env !== undefined ? WP_ADMIN_USER.localPassword : WP_ADMIN_USER.password,
    WP_BASE_URL = process.env.npm_config_env !== undefined ? WP_ADMIN_USER.local : WP_ADMIN_USER.live,
    WP_ROOT_DIR = '',
    WP_ENV_TYPE = 'external',
    WP_DOCKER_CONTAINER = '',
    WP_DOCKER_ROOT_DIR = '',
    WP_SSH_USERNAME = 'ubuntu',
    WP_SSH_ADDRESS = '51.91.147.85',
    WP_SSH_KEY = '/Users/mathieu/.ssh/id_rsa',
    WP_SSH_ROOT_DIR = '/var/www/html/mai.e2e.rocketlabsqa.ovh/'
    // WP_SSH_ADDRESS = '51.68.87.127',
    // WP_SSH_KEY = '/Users/leemichael/.ssh/id_rsa',
    // WP_SSH_ROOT_DIR = '/var/www/e2e.rocketlabsqa.ovh/htdocs/'
} = process.env;

const SCENARIO_URLS = {
    /**
     * The value will hold the url paths
     */
    home: {
        path: ''
    },
    llcss: {
        path: 'lazyload_css_background_images'
    },
    noJsLlcss: {
        path: 'lazyload_css_background_images',
        disableJs: true
    },
    elementorLlcss: {
        path: 'elementor-overlay'
    },
    delayJs: {
        path: ''
    },
    delayJsMobile: {
        path: '',
        mobile: true,
    }
}

export { 
    WP_USERNAME,
    WP_PASSWORD,
    WP_BASE_URL,
    WP_ROOT_DIR,
    WP_ENV_TYPE,
    WP_DOCKER_CONTAINER,
    WP_DOCKER_ROOT_DIR,
    WP_SSH_USERNAME,
    WP_SSH_ADDRESS,
    WP_SSH_KEY,
    WP_SSH_ROOT_DIR,
    SCENARIO_URLS
};
```

The first thing to check is that you get an SSH error it seems: `ubuntu@51.91.147.85: Permission denied (publickey)`.

@Mai-Saad 
- Can you access the server with ssh? `ssh ubuntu@51.91.147.85`
- Are you sure about the configuration of `WP_SSH_KEY`?
- At some point, you mentioned having 2 different SSH keys, and we removed one of them from the server. Can you maybe simplify your SSH setup by removing the additional key to ensure you are using the correct one?

**Comment by MathieuLamiot** [comment]
SSH key changed and the SSH error does not happen anymore, as per :https://wp-media.slack.com/archives/CUT7FLHF1/p1717736400600109

But the new plugin upload still fails

**Comment by Mai-Saad** [comment]
working after removing / from `live:'http://mai.e2e.rocketlabsqa.ovh' + change permissions to 777 on env, `
