### ISSUE TITLE
Clarify Rocket-E2E documentation with latest changes and questions

### ISSUE THREAD

**Issue by MathieuLamiot** [wp-media/wp-rocket-e2e#99]
Update this doc: https://www.notion.so/wpmedia/Rocket-E2E-Test-Automation-using-Cucumber-Playwright-aecad10ae0c14a11aa609881a9d1230b?pvs=4

With details following the questions we had recently:
- https://wp-media.slack.com/archives/CUKB44GNN/p1717504446454669 : explain the different configuration/Settings and what is needed/what is not.
- https://wp-media.slack.com/archives/CUKB44GNN/p1717505852515299 : Explain what to put in previous/next release. Maybe a link to https://www.notion.so/wpmedia/Generate-a-Branch-Zip-File-29d931ad50e945dab8df5a4302ea948a?pvs=4 ?
- https://wp-media.slack.com/archives/CUKB44GNN/p1717516851539499 
- https://wp-media.slack.com/archives/CUKB44GNN/p1717517467087399 : How to check on a quick test plan that the setup is done properly? Expected results?

Maybe consider moving this documentation to a docs folder in the repo directly, to ease its maintenance?

**Comment by Khadreal** [comment]
Updated the doc exxcept for the last item on the list. Do we have to list out each test and expected results ?

**Comment by MathieuLamiot** [comment]
> Updated the doc exxcept for the last item on the list. Do we have to list out each test and expected results ?

Listing all that would be overkill I think? What I had in mind was more of a quick test that we would have, to make sure the E2E setup is OK. I'm thinking maybe smoke tests? We could just say "run this command, after 1 minute, you should get this in the console and no errors. It means basic E2E setup is working". WDYT?

**Comment by Khadreal** [comment]
Okay, that makes sense. I'll update the doc with a smoke test and the expected result

**Comment by Khadreal** [comment]
We don't currently have anything to confirm if basic setup is fine or not, I created a draft PR https://github.com/wp-media/wp-rocket-e2e/pull/112, let me know if this is okay or we need to check for other features

**Comment by MathieuLamiot** [comment]
What I would have in mind for a healthcheck:
- Check SSH is OK (like you did)
- Check that the e2e website is accessible, and that the login is OK to get into wp-admin

**Comment by MathieuLamiot** [comment]
@Khadreal Hello, I see this is in progress for more than a week. Are there any blockers or on-going discussions? Thanks

**Comment by jeawhanlee** [comment]
Looks good to me.
